spring:
  output.ansi.enabled: ALWAYS
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
  datasource:
    url: jdbc:postgresql://rc1b-enk036iglr1em2qx.mdb.yandexcloud.net:6432/inotes
    username: iliya132
    driverClassName: org.postgresql.Driver
logging:
  level:
    org.springframework.web: ERROR
    ru.iliya132: DEBUG
  file:
    name: logs/i-note.log